### ISSUE TITLE
Pacakge not found in ROS2 

### ISSUE THREAD

**Issue by Arcewoose** [adityakamath/tof_imager_ros#2]
Hello, thank you for distributing this good materials.
But I had a problem with my ROS2 humble package couldn't launch the `vl53l5cx_ros` package and  `tof_imager_launch.py`.

 * OS: Ubuntu 23.10 LTS
 * ROS2 version:  ROS2 Humble 
 * Working structure: Local PC(WSL) --> Raspberrypi 5(conneted by SSH, ubuntu 23.10)
 
In the description,  
* Build the package and run the launch file: `ros2 launch vl53l5cx_ros tof_imager_launch.py`
 I had cloned `tof_sensor_python` repository to ROS2 workspace, and completed build.
   * command by  `colcon build`
 
But my ROS2 work space and all packages could't find and build the package that `vl53l5cx_ros` when I launched by `ros2 launch vl53l5cx_ros tof_imager_launch.py`.

Is there any way to build that package? or other way to launch?

**Comment by adityakamath** [comment]
Hey, thanks for pointing this out. I had changed the name of the package to tof_imager_ros, so you should be able to run it using ```ros2 launch tof_imager_ros tof_imager_launch.py```

I will keep this issue open, as I need to change the README. I'll close it when its updated

**Comment by Arcewoose** [comment]
Thanks for reply, but I got one more question. 
As you comment, I could find package.
but when I launched `tof_imager_launch.py`, this error message is shown.
* ` - NameError: name 'sensehat_config_path' is not defined`
*  `- InvalidFrontendLaunchFileError: The launch file may have a syntax error, or its format is unknown`
 How could I define this path? as I known, senseHAT is a communication module with rpi.

**Comment by adityakamath** [comment]
Once again, a result of my weekend late-night coding sessions. I copied the launch file from my senseHAT repo and updated it, forgot to rename the variable. 

Should be fixed now.

**Comment by Arcewoose** [comment]
Thanks for reply, just one more question!
the senseHAT problem was solved.
but when I launched `tof_imager_launch.py`, this error message is shown.

``` (myenv) peav@bot1://home/peav/ros2_humble/src/tof_imager_ros$ ros2 launch tof_imager_ros tof_imager_launch.py
[INFO] [launch]: All log files can be found below /home/peav/.ros/log/2024-06-07-10-24-43-564223-bot1-7452
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tof_imager_publisher-1]: process started with pid [7463]
[tof_imager_publisher-1] [INFO] [1717723485.170278519] [tof_imager]: Initialized
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/tof_imager'
```
* Is there any hardware problem or something else to fail the initialization of configure state?
* We're almost there to get the solution!

**Comment by adityakamath** [comment]
Hey, I fixed the documentation and the launch file for the above errors. For this last one, it seems like your sensor is failing in the on_configure method, it may be a hardware problem I think. Before launching the file, can you check using the sensor's example code to see if everything is OK. 

Meanwhile, I will try to make some time and try this out with the sensor I have as well.

**Comment by adityakamath** [comment]
I'm closing this issue and made a new issue for this latest error..
