### ISSUE TITLE
Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/tof_imager'

### ISSUE THREAD

**Issue by adityakamath** [adityakamath/tof_imager_ros#3]
Thanks for reply, just one more question!
the senseHAT problem was solved.
but when I launched `tof_imager_launch.py`, this error message is shown.

``` (myenv) peav@bot1://home/peav/ros2_humble/src/tof_imager_ros$ ros2 launch tof_imager_ros tof_imager_launch.py
[INFO] [launch]: All log files can be found below /home/peav/.ros/log/2024-06-07-10-24-43-564223-bot1-7452
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tof_imager_publisher-1]: process started with pid [7463]
[tof_imager_publisher-1] [INFO] [1717723485.170278519] [tof_imager]: Initialized
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/tof_imager'
```
* Is there any hardware problem or something else to fail the initialization of configure state?
* We're almost there to get the solution!

_Originally posted by @SewoongPark in https://github.com/adityakamath/tof_imager_ros/issues/2#issuecomment-2153694736_

**Comment by EthanolWu** [comment]
Hi,
I faced the same issue, but I finally figured it out. I didn't have permission to access the I2C device (/dev/i2c-1). After changing the permission of the I2C device to 666, everything works fine now.
Hope this helps!

**Comment by adityakamath** [comment]
Hey, thanks for sharing the solution @EthanolWu. I'll close this issue now. :)

**Comment by patrickcal99** [comment]
Good afternoon, I am also experiencing the exact same error, however unlike the other user I have installed all the necessary permissions, moreover I am using the VL53L5CX -STEAL sensor from st microelectronix, so the connection I made was as follows : SDA and SCL in their respective i2c pins, GND to ground, AVDD, IOVDD and PWREN all 3 to 3.3 volts and then I tried leaving LPn floating or connected to 3.3 volts. The connection I'm sure is correct, though I can't configure the sensor despite it being detected with the command : “sudo i2cdetect -y 1”. Could you tell me the reason? I would be grateful to you for life

**Comment by adityakamath** [comment]
@patrickcal99 are you able to access the sensor without the ROS package? using just the Python library?
